
name: Release

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install pnpm and Node.js
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Step 3: Get pnpm store directory and cache dependencies
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Build the project
      - name: Build the project
        run: pnpm build

      # 调试步骤：输出环境变量
      - name: Debug environment variables
        run: |
          if [ -z "${{ secrets.NUXT_HUB_PROJECT_KEY }}" ]; then
            echo "NUXT_HUB_PROJECT_KEY is empty: true"
          else
            echo "NUXT_HUB_PROJECT_KEY is empty: false"
          fi

          if [ -z "${{ secrets.NUXT_HUB_USER_TOKEN }}" ]; then
            echo "NUXT_HUB_USER_TOKEN is empty: true"
          else
            echo "NUXT_HUB_USER_TOKEN is empty: false"
          fi
